# golangci-lint configuration for cryptofunk
# Compatible with golangci-lint v1.55.2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Standard go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code
    - gofmt         # Check formatting
    - goimports     # Check import order
    - misspell      # Check for misspelled words
    - goconst       # Find repeated strings that could be constants
    - gosec         # Security-focused linting
    - bodyclose     # Check HTTP response bodies are closed
    - noctx         # Detect HTTP requests without context
    - rowserrcheck  # Check SQL rows.Err is checked
    - sqlclosecheck # Check SQL rows/statements are closed

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close

  gosec:
    excludes:
      - G104  # Audit errors not checked (handled by errcheck)
      - G304  # File path provided as input (false positives in config loading)

  govet:
    check-shadowing: false
    enable-all: true
    disable:
      - fieldalignment  # Don't enforce struct field alignment
      - shadow          # Allow variable shadowing

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false

  goimports:
    local-prefixes: github.com/ajitpratap0/cryptofunk

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

    # Exclude known issues in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Ignore main packages (they handle errors with log.Fatal)
    - path: cmd/
      text: "Error return value"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
